### PR TITLE
Make CodeGenerator and Context overridable

### PR DESCRIPTION
**Pull request by ThiefMaster**
It's probably not needed very often, but subclassing e.g. the Environment to use a custom class for it would be so much cleaner than having to monkey-patch or fork.

### CODE REVIEW

**Comment by untitaker** [comment]
I'm really confused by your commit referencing the PR itself but the diff checks out.

**Comment by ThiefMaster** [comment]
Initially I was going to open a separate PR, then I remembered that the `hub` util can convert an existing issue in a PR.

**Comment by untitaker** [comment]
I see, I thought that functionality has been removed from Github.

**Comment by ThiefMaster** [comment]
It's deprecated (not sure why, seems to be useful) according to the output of the command:

> Warning: Issue to pull request conversion is deprecated and might not work in the future.

**Comment by untitaker** [comment]
Thanks, merged!

**Comment by untitaker** [comment]
Regarding that hub feature: https://github.com/github/hub/commit/4f70dd126f46dec14fc341c97c18efae417743c7

**Pull request closed without merging**
