### PR TITLE
Add test notequalto

### PR DESCRIPTION
**Pull request by brmzkw**
I guess the filters `test_test` (testing `if value`) and `test_not` (testing `if not value`) would be great additions too.

### CODE REVIEW

**Comment by ThiefMaster** [comment]
I think you can already use `is not equalto something`.

**Comment by brmzkw** [comment]
I need to use `notequalto` in a `select` filter, such `astring.split('/') | select('notequalto', '')`

**Comment by mitsuhiko** [comment]
Why not use ``{{ users|rejectattr("email", "equalto", "foo@bar.valid") }}``?

**Comment by brmzkw** [comment]
You save my day. I didn't know `rejectattr` (or `reject` in my case) existed. Thanks a lot :)

**Pull request closed without merging**
