### PR TITLE
Fix typos and grammar in Readme

### PR DESCRIPTION
**Pull request by jeffwidman**

### CODE REVIEW

**Comment by untitaker** [comment]
Seems fine, thanks!

**Comment by davidism** [comment]
This still sounds awkward.  The point of the sentence is to succinctly state what Jinja's philosophy is.  If you're going to change it, make it flow better, don't just fix the grammar.

> Application logic is for the controller, but don't make the template designer's life difficult by restricting functionality too  much.

**Comment by untitaker** [comment]
@davidism I've applied your changes too, thanks!

**Comment by jeffwidman** [comment]
:+1:

**Pull request merged**
