### PR TITLE
Improve with_metaclass()

### PR DESCRIPTION
**Pull request by snoack**
With mitsuhiko/flask#1539 the `with_metaclass` function got impoved in Flask, see the comments there. So we should use the same implementation in jinja2 as well. Note that this PR merely copied over the code from Flask.

### CODE REVIEW

**Comment by davidism** [comment]
We should really have a common library for this stuff.  I know @untitaker has been talking about that with Werkzeug in the past.

**Comment by untitaker** [comment]
We do, it's called six. I don't recall talking about moving compat into an external lib.

On 5 August 2015 18:40:31 CEST, David Lord <notifications@github.com> wrote:
>We should really have a common library for this stuff.  I know
>@untitaker has been talking about that with Werkzeug in the past.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/jinja2/pull/471#issuecomment-128065797

-- 
Sent from my phone. Please excuse my brevity.

**Comment by snoack** [comment]
Not that I'm a particular fan of six. But out of curiosity, why isn't
Werkzeug/Jinja2/Flask using six?

**Comment by untitaker** [comment]
The current compat module is reasonably small to be vendored. We'd use very little of six, and afaik it does a lot of magical stuff.

On 5 August 2015 19:13:11 CEST, Sebastian Noack <notifications@github.com> wrote:
>Not that I'm a particular fan of six. But out of curiosity, why isn't
>Werkzeug/Jinja2/Flask using six?
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/jinja2/pull/471#issuecomment-128077158

-- 
Sent from my phone. Please excuse my brevity.

**Comment by davidism** [comment]
@untitaker I didn't mean move to six, I just remembered you talking about extracting common stuff from Werkzeug, not specifically compat.  My point was that it's the same code in each project.

**Comment by untitaker** [comment]
Yeah, but I didn't really mean compat, but contrib.

On 5 August 2015 19:20:09 CEST, David Lord <notifications@github.com> wrote:
>@untitaker I didn't mean move to six, I just remembered you talking
>about extracting common stuff from Werkzeug, not specifically compat. 
>My point was that it's the same code in each project.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/jinja2/pull/471#issuecomment-128081932

-- 
Sent from my phone. Please excuse my brevity.

**Comment by snoack** [comment]
Well, its actually not the same code except for some particular
implementations like metaclasses and a few trivial declarations. Most code
in the specific _compat modules however is tooled towards the project
specific needs. Which I'd agree is a reasonable approach.

However, if there is a dependency on six anyway, I wonder why we don't use
their with_metaclass function. On the other hand I'd personally would
rather get rid of six completely.

**Comment by untitaker** [comment]
There is no dependency on six.

On 5 August 2015 19:39:52 CEST, Sebastian Noack <notifications@github.com> wrote:
>Well, its actually not the same code except for some particular
>implementations like metaclasses and a few trivial declarations. Most
>code
>in the specific _compat modules however is tooled towards the project
>specific needs. Which I'd agree is a reasonable approach.
>
>However, if there is a dependency on six anyway, I wonder why we don't
>use
>their with_metaclass function. On the other hand I'd personally would
>rather get rid of six completely.
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/mitsuhiko/jinja2/pull/471#issuecomment-128086577

-- 
Sent from my phone. Please excuse my brevity.

**Comment by snoack** [comment]
Sorry, misread your comment above. Deleted my comment. I agree that having vendored `_compat` modules in the respective projects is a reasonable approach, given that they are fairly trivial and tooled towards the project-specific needs. So I suppose there is no objection merging this pull request?

**Comment by untitaker** [comment]
Thanks!

**Pull request merged**
